site_name: Documentación Calculadora
site_url: https://gatherh.github.io/Calculadora

theme:
  name: material
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - search.highlight
    - content.code.copy

plugins:
  - search:
      lang: es

nav:
  - Inicio: index.md
  - Instalación: instalacion.md
  - Uso: uso.md
