name: Publicar Documentacion

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar MkDocs con tema Material
        run: pip install mkdocs-material

      - name: Construir y publicar
        run: mkdocs gh-deploy --force